# Generated by Django 4.2.14 on 2026-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['visibility'], name='offers_visibil_69dccc_idx'),
        ),
    ]
